name: URLhaus_Feed

on:
  schedule:
    - cron: '0 16,22,4,10 * * *'  # UTC, 對應 UTC+8 的 0,6,12,18
  workflow_dispatch:

jobs:
  build-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run Python script
        run: python generate_urlhaus.py   # <- 執行根目錄的 py 檔

      - name: Commit and push feed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add urlhaus_feed.txt
          git commit -m "Update URLhaus feed" || echo "No changes"
          git push
