name: URLhaus_feed

on:
  schedule:
    - cron: '0 16,22,4,10 * * *'  # UTC, 對應 UTC+8 的 0,6,12,18
  workflow_dispatch:

jobs:
  build-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate TXT feed from URLhaus CSV
        run: |
          pip install requests
          python - << 'EOF'
import requests
import csv

# URLhaus CSV 最近惡意 URL
csv_url = "https://urlhaus.abuse.ch/downloads/csv_recent/"

resp = requests.get(csv_url)
resp.raise_for_status()
lines = resp.text.splitlines()

reader = csv.DictReader(lines)

with open("urlhaus_feed.txt", "w", encoding="utf-8") as f:
    for row in reader:
        url = row.get("url")
        if url:
            f.write(url + "\n")

print("已生成 URLhaus_feed.txt")
EOF

      - name: Commit and push feed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add urlhaus_feed.txt
          git commit -m "Update URLhaus feed" || echo "No changes"
          git push
